version: "3"

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
